torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_train_data_gt_with_gps_perturb_slice_generic.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split train --out-dir all_train_maps_gt_v2_500m --start-idx 0 --end-idx 5000
torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_train_data_gt_with_gps_perturb_slice_generic.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split train --out-dir all_train_maps_gt_v2_500m --start-idx 5000 --end-idx 10000
torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_train_data_gt_with_gps_perturb_slice_generic.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split train --out-dir all_train_maps_gt_v2_500m --start-idx 10000 --end-idx 15000
torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_train_data_gt_with_gps_perturb_slice_generic.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split train --out-dir all_train_maps_gt_v2_500m --start-idx 15000 --end-idx 20000
torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_train_data_gt_with_gps_perturb_slice_generic.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split train --out-dir all_train_maps_gt_v2_500m --start-idx 20000 --end-idx 25000
torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_train_data_gt_with_gps_perturb_slice_generic.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split train --out-dir all_train_maps_gt_v2_500m --start-idx 25000 --end-idx 100000


torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_val_data_gt_with_gps_perturb_slice_generic.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split val --out-dir all_val_maps_gt_v2_500m --start-idx 0 --end-idx 3000

torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_val_data_gt_with_gps_perturb_slice_generic.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split val --out-dir all_val_maps_gt_v2_500m --start-idx 3000 --end-idx 6020

# torchpack dist-run -np 1 python tools/create_data_train_parallel/visualize_and_get_gps_train_data_gt_with_gps_perturb_slice_generic_debug.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --mode gt --split train --out-dir all_train_maps_gt_v2_500m --start-idx 0 --end-idx 123580